# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SAMPLE CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
      env:
        CI: false

    - name: List output files
      run: find build/ -print

    - name: 📂 Sync files
    uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.digitalnative.id
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /